// <auto-generated />
using System;
using KShop.Shipments.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KShop.Shipments.Persistence.Migrations
{
    [DbContext(typeof(ShipmentContext))]
    [Migration("20210601194659_InitialCommit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("KShop.Shipments.Persistence.Entities.Shipment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalID")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastCheckingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PendingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
