// <auto-generated />
using System;
using KShop.Payments.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KShop.Payments.Persistence.Migrations
{
    [DbContext(typeof(PaymentsContext))]
    partial class PaymentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KShop.Payments.Persistence.Entities.Payment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ExternalPaymentID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("char(36)");

                    b.Property<int>("PaymentProvider")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("KShop.Payments.Persistence.Entities.PaymentLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PaymentID")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PaymentID");

                    b.ToTable("PaymentLogs");
                });

            modelBuilder.Entity("KShop.Payments.Persistence.Entities.Payment", b =>
                {
                    b.OwnsOne("KShop.Payments.Persistence.Entities.Money", "Money", b1 =>
                        {
                            b1.Property<Guid>("PaymentID")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Amount")
                                .HasColumnType("decimal(65,30)")
                                .HasDefaultValue(0m);

                            b1.Property<string>("Currency")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Currency")
                                .HasColumnType("longtext CHARACTER SET utf8mb4")
                                .HasDefaultValue("RUB");

                            b1.HasKey("PaymentID");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentID");
                        });
                });

            modelBuilder.Entity("KShop.Payments.Persistence.Entities.PaymentLog", b =>
                {
                    b.HasOne("KShop.Payments.Persistence.Entities.Payment", "Payment")
                        .WithMany("Logs")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
