version: '3.9'
services:
    dbs_products:
        image: mysql:latest
        restart: always
        environment: 
            MYSQL_DATABASE: 'db_products'
            MYSQL_USER: 'asd'
            MYSQL_PASSWORD: 'asd'
            MYSQL_ROOT_PASSWORD: 'asd'
        ports:
            - '3306:3306'
        expose: 
            - '3306'
        networks:
            kshop_network:
                aliases:
                    - dbs_products
        volumes:
            - vol-dbs_products:/var/lib/mysql

    dbs_orders:
        image: mysql:latest
        restart: always
        environment: 
            MYSQL_DATABASE: 'db_orders'
            MYSQL_USER: 'asd'
            MYSQL_PASSWORD: 'asd'
            MYSQL_ROOT_PASSWORD: 'asd'
        ports:
            - '3307:3306'
        expose: 
            - '3307'
        networks:
            kshop_network:
                aliases:
                    - dbs_orders
        volumes:
            - vol-dbs_orders:/var/lib/mysql

    dbs_payments:
        image: mysql:latest
        restart: always
        environment: 
            MYSQL_DATABASE: 'db_payments'
            MYSQL_USER: 'asd'
            MYSQL_PASSWORD: 'asd'
            MYSQL_ROOT_PASSWORD: 'asd'
        ports:
            - '3308:3306'
        expose: 
            - '3308'
        networks:
            kshop_network:
                aliases:
                    - dbs_payments
        volumes:
            - vol-dbs_payments:/var/lib/mysql

    dbs_shipments:
        image: mysql:latest
        restart: always
        environment: 
            MYSQL_DATABASE: 'db_shipments'
            MYSQL_USER: 'asd'
            MYSQL_PASSWORD: 'asd'
            MYSQL_ROOT_PASSWORD: 'asd'
        ports:
            - '3309:3306'
        expose: 
            - '3309'
        networks:
            kshop_network:
                aliases:
                    - dbs_shipments
        volumes:
            - vol-dbs_shipments:/var/lib/mysql

    msgb_rabbitmq:
        image: 'rabbitmq:3.8.9-management-alpine'
        hostname: 'rabbit1'
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'
        environment: 
            RABBITMQ_DEFAULT_VHOST: "/"
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: 'guest'
            RABBITMQ_DEFAULT_PASS: 'guest'
        networks:
            kshop_network:
                aliases:
                    - msgb_rabbitmq
        volumes:
            - vol-msgb_rabbitmq:/var/lib/rabbitmq/mnesia
            #- "./docker/rabbitmq/enabled_plugins.txt:/etc/rabbitmq/enabled_plugins"

    redis:
        image: 'redis:alpine'
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --requirepass asd
        environment:
            - REDIS_REPLICATION_MODE=master
        networks:
            kshop_network:
                aliases:
                    - redis
        volumes:
            - vol-redis:/var/lib/redis
            #- "./volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf"

    adminer:
        image: adminer
        restart: always
        ports:
        - 9080:8080
        networks:
            kshop_network:
                aliases:
                - adminer
    
    log_seq:
        image: datalust/seq:latest
        restart: always
        environment: 
            HOST_PATH_TO_SEQ: '/data'
            ACCEPT_EULA: 'Y'
        ports: 
            - 5080:80
            - 5341:5341
        volumes:
            - vol-log_seq:/data
        networks:
            kshop_network:
                aliases:
                - log_seq
    
    metr_influxdb:
        restart: always
        image: influxdb:1.8
        ports:
            - 8086:8086
            - 8088:8088
        environment: 
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_ADMIN_USER: influx
            INFLUXDB_ADMIN_PASSWORD: asdasdasd
            INFLUX_DB: db_kshop_metrics
            # Подставляется при авторизации в CLI
            
            INFLUX_USERNAME: influx
            INFLUX_PASSWORD: asdasdasd

            INFLUXDB_REPORTING_DISABLED: "false"
            INFLUXDB_BIND_ADDRESS: 0.0.0.0:8088
            # Мониторинг самого InfluxDb
            INFLUXDB_MONITOR_STORE_ENABLED: "true"
            INFLUXDB_MONITOR_STORE_DATABASE: _internal
            INFLUXDB_MONITOR_STORE_INTERVAL: 10s

        volumes:
            - vol-metr_influxdb:/var/lib/influxdb
        networks:
            kshop_network:
                aliases:
                - metr_influxdb
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: 1g

    metr_chronograf:
        restart: always
        image: chronograf:1.8
        ports:
            - 8888:8888
        environment:
            - INFLUXDB_URL=http://metr_influxdb:8086
            - INFLUXDB_USERNAME=influx
            - INFLUXDB_PASSWORD=asdasdasd
        volumes:
            - vol-metr_chronograf:/var/lib/chronograf
        depends_on: 
            - metr_influxdb
        networks:
            kshop_network:
                aliases:
                - metr_chronograf

    metr_grafana:
        restart: always
        image: grafana/grafana
        ports:
            - 3000:3000
        environment: 
            - GF_SECURITY_ADMIN_USER=grafana
            - GF_SECURITY_ADMIN_PASSWORD=asdasdasd
        depends_on: 
            - metr_influxdb
        volumes:
            - vol-metr_grafana:/var/lib/grafana
        networks:
            kshop_network:
                aliases:
                - metr_grafana

    trace_jaeger:
        restart: always
        image: jaegertracing/all-in-one
        ports: 
            - 5775:5775/udp # zipkin.thrift - deprecated
            - 6831:6831/udp # accept jaeger.thrift over compact thrift protocol
            - 6832:6832/udp # accept jaeger.thrift over binary thrift protocol
            - 5778:5778     # serve configs
            - 16686:16686   # serve frontend
            - 14268:14268   # accept jaeger.thrift directly from clients
            - 14250:14250   # accept model.proto
            - 9411:9411     # Zipkin compatible endpoint (optional)
        expose:
            - '16686'
        environment: 
            COLLECTOR_ZIPKIN_HOST_PORT: 9411
            # SPAN_STORAGE_TYPE: elasticsearch
            # ES_SERVER_URLS: http://log_elasticsearch:9200
        # volumes:
        #     - vol-trace_jaeger:

        networks: 
            kshop_network:
                aliases: 
                - trace_jaeger
                
    
    # log_elasticsearch:
    #     restart: always
    #     #container_name: log_elasticsearch
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    #     ports:
    #         - 9200:9200
    #         - 9300:9300
    #     environment:
    #         - xpack.security.enabled=false
    #         - discovery.type=single-node
    #         # - node.name=es01
    #         # - cluster.name=es-docker-cluster
    #         # - discovery.type=single-node
    #         # - bootstrap.memory_lock=true
    #         # - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    #         # - "ELASTIC_PASSWORD:changeme"

    #         #- xpack.security.enabled=true                    
    #     volumes:
    #         - vol-log_elastic:/usr/share/elasticsearch/data
    #         #- ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    #     networks:
    #         kshop_network:
    #             aliases:
    #             - log_elasticsearch
                
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #         nofile:
    #             soft: 65536
    #             hard: 65536

    #     mem_limit: 2g
            
    # log_kibana:
    #     restart: always
    #     #container_name: log_kibana    
    #     image: docker.elastic.co/kibana/kibana:7.12.0
    #     ports:
    #         - 5601:5601
    #     environment:
    #         #ELASTICSEARCH_URL: "http://log_elasticsearch:9200"
    #         ELASTICSEARCH_HOSTS: "http://log_elasticsearch:9200"
    #         ELASTICSEARCH_USERNAME: "kibana"
    #         ELASTICSEARCH_PASSWORD: "changeme"
    #     depends_on:
    #         - log_elasticsearch   
    #     # volumes:  
    #     #     - ./configs/kibana.yml:/usr/share/kibana/config/kibana.yml
    #     networks:
    #         kshop_network:
    #             aliases:
    #             - log_kibana

    # metr_influxdb2:
    #     restart: always
    #     image: influxdb:2.0.4
    #     ports:
    #         - 8086:8086
    #     environment: 
    #         - DOCKER_INFLUXDB_INIT_USERNAME=influx
    #         - DOCKER_INFLUXDB_INIT_PASSWORD=asdasdasd
    #         - DOCKER_INFLUXDB_INIT_ORG=kshop
    #         - DOCKER_INFLUXDB_INIT_BUCKET=appmetrics
    #     volumes:
    #         - vol-metr_influxdb2:/var/lib/influxdb2
    #     networks:
    #         kshop_network:
    #             aliases:
    #             - metr_influxdb2
    #     mem_limit: 1g


networks:
    kshop_network:
        name: kshop_network

volumes:
    vol-dbs_products: {}
    vol-dbs_orders: {}
    vol-dbs_payments: {}
    vol-dbs_shipments: {}
    vol-msgb_rabbitmq: {}
    vol-log_seq: {}
    vol-redis: {}
    vol-log_elastic: {}
    vol-metr_influxdb: {}
    vol-metr_influxdb2: {}
    vol-metr_grafana: {}
    vol-metr_chronograf: {}
    #vol-trace_jaeger: {}