version: '3.9'
services:

    api_orders:
        image: kshop.orders.webapi:latest
        restart: always
        environment: 
            ASPNETCORE_ENVIRONMENT: 'Staging'
        ports:
            - '5000:80'
            - '5001:443'
        expose: 
            - '5000'
        networks:
            kshop_network:
                aliases:
                    - api_orders
networks:
    kshop_network:
        name: kshop_network