// <auto-generated />
using System;
using KShop.Products.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KShop.Products.Persistence.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20210527120853_InitialCommit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KShop.Products.Persistence.Entities.Product", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.ProductPosition", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ProductID")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Quantity")
                        .HasColumnType("int unsigned");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductPositions");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.ProductReserve", b =>
                {
                    b.Property<ulong>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("CustomerID")
                        .HasColumnType("bigint unsigned");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("char(36)");

                    b.Property<ulong>("ProductID")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Quantity")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductReserves");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.Product", b =>
                {
                    b.OwnsOne("KShop.Communications.Contracts.ValueObjects.Money", "Money", b1 =>
                        {
                            b1.Property<ulong>("ProductID")
                                .HasColumnType("bigint unsigned");

                            b1.Property<string>("Currency")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Currency")
                                .HasColumnType("longtext CHARACTER SET utf8mb4")
                                .HasDefaultValue("RUB");

                            b1.Property<decimal>("Price")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("Price")
                                .HasColumnType("decimal(65,30)")
                                .HasDefaultValue(0m);

                            b1.HasKey("ProductID");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductID");
                        });
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.ProductPosition", b =>
                {
                    b.HasOne("KShop.Products.Persistence.Entities.Product", "Product")
                        .WithMany("Positions")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.ProductReserve", b =>
                {
                    b.HasOne("KShop.Products.Persistence.Entities.Product", "Product")
                        .WithMany("Reserves")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
