// <auto-generated />
using System;
using KShop.Products.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KShop.Products.Persistence.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("KShop.Products.Persistence.Entities.Product", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.ProductPosition", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("ProductID")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Quantity")
                        .HasColumnType("int unsigned");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductPositions");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.ProductReserve", b =>
                {
                    b.Property<uint>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("CustomerID")
                        .HasColumnType("bigint unsigned");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("char(36)");

                    b.Property<uint>("ProductID")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Quantity")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductReserves");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.Product", b =>
                {
                    b.OwnsOne("KShop.Communications.Contracts.ValueObjects.Money", "Money", b1 =>
                        {
                            b1.Property<uint>("ProductID")
                                .HasColumnType("bigint unsigned");

                            b1.Property<string>("Currency")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("longtext")
                                .HasDefaultValue("RUB")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Price")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("decimal(65,30)")
                                .HasDefaultValue(0m)
                                .HasColumnName("Price");

                            b1.HasKey("ProductID");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductID");
                        });

                    b.Navigation("Money");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.ProductPosition", b =>
                {
                    b.HasOne("KShop.Products.Persistence.Entities.Product", "Product")
                        .WithMany("Positions")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.ProductReserve", b =>
                {
                    b.HasOne("KShop.Products.Persistence.Entities.Product", "Product")
                        .WithMany("Reserves")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KShop.Products.Persistence.Entities.Product", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Reserves");
                });
#pragma warning restore 612, 618
        }
    }
}
